# Generated by Django 3.2.9 on 2021-11-21 20:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpl_name', models.CharField(max_length=60, verbose_name='Complaint name')),
                ('cpl_details', models.CharField(max_length=300, verbose_name='Complaint details')),
                ('cpl_creation_date', models.DateField(auto_now_add=True)),
                ('cpl_deadline', models.DateTimeField()),
                ('cpl_closing_date', models.DateField(auto_now_add=True)),
                ('is_cpl_finished', models.BooleanField(default=False)),
                ('closing_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closing', to=settings.AUTH_USER_MODEL)),
                ('reporting_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reporting', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tsk_name', models.CharField(max_length=60, verbose_name='Name')),
                ('tsk_details', models.CharField(max_length=200, verbose_name='Details')),
                ('tsk_creation_date', models.DateField(auto_now_add=True)),
                ('tsk_deadline', models.DateField()),
                ('tsk_closing_date', models.DateField(auto_now_add=True)),
                ('is_tsk_finished', models.BooleanField(default=False)),
                ('is_tsk_immediate', models.BooleanField(default=False)),
                ('assigned_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned', to=settings.AUTH_USER_MODEL)),
                ('complaint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='complaints.complaint')),
            ],
        ),
    ]
