# Generated by Django 3.2.9 on 2021-11-21 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='cpl_deadline',
            field=models.DateField(),
        ),
    ]
