# Generated by Django 3.2.9 on 2021-11-21 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_alter_complaint_cpl_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='cpl_closing_date',
            field=models.DateField(verbose_name='Closing Date'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='cpl_creation_date',
            field=models.DateField(auto_now_add=True, verbose_name='Reporting Date'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='cpl_deadline',
            field=models.DateField(verbose_name='Deadline'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='is_cpl_finished',
            field=models.BooleanField(default=False, verbose_name='Complaint is closed'),
        ),
        migrations.AlterField(
            model_name='task',
            name='is_tsk_finished',
            field=models.BooleanField(default=False, verbose_name='Task finished?'),
        ),
        migrations.AlterField(
            model_name='task',
            name='is_tsk_immediate',
            field=models.BooleanField(default=False, verbose_name='Task immediate?'),
        ),
        migrations.AlterField(
            model_name='task',
            name='tsk_closing_date',
            field=models.DateField(verbose_name='Closing Date'),
        ),
        migrations.AlterField(
            model_name='task',
            name='tsk_creation_date',
            field=models.DateField(auto_now_add=True, verbose_name='Creation Date'),
        ),
        migrations.AlterField(
            model_name='task',
            name='tsk_deadline',
            field=models.DateField(verbose_name='Deadline'),
        ),
    ]
