# Generated by Django 3.2.9 on 2021-11-21 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0004_auto_20211121_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='cpl_closing_date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Closing Date'),
        ),
        migrations.AlterField(
            model_name='task',
            name='tsk_closing_date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Closing Date'),
        ),
    ]
